# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filterWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

from testing.filterWindow import filterWindow


class filterWindowEx(filterWindow):

    def __init__(self,Parent):
        super().__init__(Parent)
        self.parent=Parent
        print(self.pushButton.text())
        self.pushButton.clicked.connect(self.accept)

    def accept(self):
        # comboVal=self.comboBox.currentText()
        filterBy=self.comboBox.currentText()
        condition=self.comboBox_2.currentText()
        line_1stValue=self.lineEdit.text()
        line_2ndValue=self.lineEdit_2.text()
        sortBy=self.comboBox_3.currentText()
        kk=self.parent.comboBox.currentText()
        print(kk)
        # industry=self.parent.getSelectedComboxValue()

        dic = {'Greater Than...': '>', 'Less Than...': '<', 'Equal To...': '=', 'Between...': 'In'}
        # print( "Select stoke,[LTP],[Change(%)],[Change Price],Vol,[Delivery Vol],[Delivery(%)],Industry,[Market Cap] from dbo.All$ inner join dbo.nayiTable on dbo.All$.Stoke=dbo.nayiTable.[Stock Name] where [Industry]= 'Chemicals'  and [{}] {} {} order by [{}] desc".format(filterBy, dic[condition], line_1stValue, sortBy))
        self.close()
        df=self.parent.filterQuery(kk,filterBy, dic[condition], line_1stValue, sortBy)
        # df=self.parent.chooseIndex(comboVal)
        self.parent.showData(df)
        self.parent.populateTableView(df)


# class filterWindow(QMainWindow):
#
#     def __init__(self, Parent):
#         super(filterWindow, self).__init__(Parent)
#         self.setupUi()
#
#     def setupUi(self):
#         MainWindow = self