# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeFrame_PDFPNGConverter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame


class HomeFrame_PDFPNGConverter(QFrame):

    def __init__(self):
        super(HomeFrame_PDFPNGConverter, self).__init__()
        self.setupUi(self)

    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(757, 434)
        Frame.setStyleSheet("\n"
"QFrame{\n"
"    border-width: 20;\n"
"    border-color: rgb(255,255,255);\n"
"    border-radius: 3;\n"
"    border-style: solid;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-width: 1;\n"
"    border-color: rgb(46, 177, 11);\n"
"    border-radius: 3;\n"
"    border-style: solid;\n"
"    background-color: rgb(46, 177, 11);\n"
"    color: rgb(254, 254, 254);        \n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"\n"
"QLabel{\n"
"    border-width: 0;\n"
"}")
        Frame.setFrameShape(QtWidgets.QFrame.Box)
        Frame.setLineWidth(10)
        Frame.setMidLineWidth(0)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(50, 25, 50, 25)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 200))
        self.label.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self._btnExportPdf2Png = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnExportPdf2Png.sizePolicy().hasHeightForWidth())
        self._btnExportPdf2Png.setSizePolicy(sizePolicy)
        self._btnExportPdf2Png.setMinimumSize(QtCore.QSize(250, 80))
        self._btnExportPdf2Png.setMaximumSize(QtCore.QSize(250, 80))
        self._btnExportPdf2Png.setStyleSheet("background-color: rgb(70, 148, 200);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/images/resources/images/pdf2pdf1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btnExportPdf2Png.setIcon(icon)
        self._btnExportPdf2Png.setIconSize(QtCore.QSize(100, 100))
        self._btnExportPdf2Png.setObjectName("_btnExportPdf2Png")
        self.verticalLayout.addWidget(self._btnExportPdf2Png, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(Frame)
        self.line.setMaximumSize(QtCore.QSize(16777215, 200))
        self.line.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(50, 25, 50, 25)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(200, 200))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self._btnPng2Pdf = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnPng2Pdf.sizePolicy().hasHeightForWidth())
        self._btnPng2Pdf.setSizePolicy(sizePolicy)
        self._btnPng2Pdf.setMinimumSize(QtCore.QSize(250, 80))
        self._btnPng2Pdf.setMaximumSize(QtCore.QSize(250, 80))
        self._btnPng2Pdf.setStyleSheet("background-color: rgb(55, 49, 118);")
        self._btnPng2Pdf.setIcon(icon)
        self._btnPng2Pdf.setIconSize(QtCore.QSize(100, 100))
        self._btnPng2Pdf.setObjectName("_btnPng2Pdf")
        self.verticalLayout_2.addWidget(self._btnPng2Pdf, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Export selected pdf pages as image file"))
        self._btnExportPdf2Png.setText(_translate("Frame", "Export PDF \n"
"to PNG"))
        self.label_2.setText(_translate("Frame", "Export image files as a single pdf file"))
        self._btnPng2Pdf.setText(_translate("Frame", "Export PNG \n"
"to PDF"))
