# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeFrame_PDFExporter2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame


class HomeFrame_PDFExporter2(QFrame):

    def __init__(self):
        super(HomeFrame_PDFExporter2, self).__init__()
        self.setupUi(self)

    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1014, 418)
        Frame.setStyleSheet("\n"
"QFrame{\n"
"    border-width: 20;\n"
"    border-color: rgb(255,255,255);\n"
"    border-radius: 3;\n"
"    border-style: solid;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-width: 1;\n"
"    border-color: rgb(46, 177, 11);\n"
"    border-radius: 3;\n"
"    border-style: solid;\n"
"    background-color: rgb(46, 177, 11);\n"
"    color: rgb(254, 254, 254);        \n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"\n"
"QLabel{\n"
"    border-width: 0;\n"
"}")
        Frame.setFrameShape(QtWidgets.QFrame.Box)
        Frame.setLineWidth(10)
        Frame.setMidLineWidth(0)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 200))
        self.label.setMaximumSize(QtCore.QSize(300, 200))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self._btnExportPdf2SinglePdf = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnExportPdf2SinglePdf.sizePolicy().hasHeightForWidth())
        self._btnExportPdf2SinglePdf.setSizePolicy(sizePolicy)
        self._btnExportPdf2SinglePdf.setMinimumSize(QtCore.QSize(250, 80))
        self._btnExportPdf2SinglePdf.setMaximumSize(QtCore.QSize(250, 80))
        self._btnExportPdf2SinglePdf.setStyleSheet("background-color: rgb(70, 148, 200);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/images/resources/images/pdf2pdf1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btnExportPdf2SinglePdf.setIcon(icon)
        self._btnExportPdf2SinglePdf.setIconSize(QtCore.QSize(100, 100))
        self._btnExportPdf2SinglePdf.setObjectName("_btnExportPdf2SinglePdf")
        self.verticalLayout.addWidget(self._btnExportPdf2SinglePdf, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(Frame)
        self.line.setMinimumSize(QtCore.QSize(2, 0))
        self.line.setMaximumSize(QtCore.QSize(2, 200))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(300, 200))
        self.label_2.setMaximumSize(QtCore.QSize(300, 200))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self._btnPdf2SeperatePdf = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnPdf2SeperatePdf.sizePolicy().hasHeightForWidth())
        self._btnPdf2SeperatePdf.setSizePolicy(sizePolicy)
        self._btnPdf2SeperatePdf.setMinimumSize(QtCore.QSize(250, 80))
        self._btnPdf2SeperatePdf.setMaximumSize(QtCore.QSize(250, 80))
        self._btnPdf2SeperatePdf.setStyleSheet("background-color: rgb(55, 49, 118);")
        self._btnPdf2SeperatePdf.setIcon(icon)
        self._btnPdf2SeperatePdf.setIconSize(QtCore.QSize(100, 100))
        self._btnPdf2SeperatePdf.setObjectName("_btnPdf2SeperatePdf")
        self.verticalLayout_2.addWidget(self._btnPdf2SeperatePdf, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(Frame)
        self.line_2.setMinimumSize(QtCore.QSize(2, 0))
        self.line_2.setMaximumSize(QtCore.QSize(2, 200))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(200, 200))
        self.label_3.setMaximumSize(QtCore.QSize(300, 200))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self._btnPdf2ImagedPdf = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnPdf2ImagedPdf.sizePolicy().hasHeightForWidth())
        self._btnPdf2ImagedPdf.setSizePolicy(sizePolicy)
        self._btnPdf2ImagedPdf.setMinimumSize(QtCore.QSize(250, 80))
        self._btnPdf2ImagedPdf.setMaximumSize(QtCore.QSize(250, 80))
        self._btnPdf2ImagedPdf.setStyleSheet("background-color: rgb(55, 49, 118);")
        self._btnPdf2ImagedPdf.setIcon(icon)
        self._btnPdf2ImagedPdf.setIconSize(QtCore.QSize(100, 100))
        self._btnPdf2ImagedPdf.setObjectName("_btnPdf2ImagedPdf")
        self.verticalLayout_3.addWidget(self._btnPdf2ImagedPdf, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Export selected pdf pages as a single pdf page"))
        self._btnExportPdf2SinglePdf.setText(_translate("Frame", "Export PDF \n"
"to Single Pdf"))
        self.label_2.setText(_translate("Frame", "Export Pdf pages as a seperate pdf pages individually"))
        self._btnPdf2SeperatePdf.setText(_translate("Frame", "Export Pdf \n"
"to Seperate Pdf"))
        self.label_3.setText(_translate("Frame", "Export Pdf as a scanned or imaged pdf."))
        self._btnPdf2ImagedPdf.setText(_translate("Frame", "Export Pdf \n"
"to Imaged Pdf"))
