# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5.QtWidgets import QFrame, QApplication
import resources

class HomeFrame(QFrame):

    def __init__(self):
        super(HomeFrame, self).__init__()
        self.setupUi()

    def setupUi(self):
        Frame = self
        Frame.setObjectName("Frame")
        Frame.resize(660, 434)
        Frame.setStyleSheet("\n"
"QFrame{\n"
"    border-width: 20;\n"
"    border-color: rgb(46, 177, 11);\n"
"    border-radius: 3;\n"
"    border-style: solid;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border-width: 1;\n"
"    border-color: rgb(46, 177, 11);\n"
"    border-radius: 3;\n"
"    border-style: solid;\n"
"    background-color: rgb(46, 177, 11);\n"
"    color: rgb(254, 254, 254);        \n"
"    font: 75 14pt \"Arial\";\n"
"}")
        Frame.setFrameShape(QtWidgets.QFrame.Box)
        Frame.setLineWidth(10)
        Frame.setMidLineWidth(0)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, 50, 50, 25)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._btnProtectPdf = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnProtectPdf.sizePolicy().hasHeightForWidth())
        self._btnProtectPdf.setSizePolicy(sizePolicy)
        self._btnProtectPdf.setMinimumSize(QtCore.QSize(0, 60))
        self._btnProtectPdf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self._btnProtectPdf.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/images/resources/images/fileLock2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btnProtectPdf.setIcon(icon)
        self._btnProtectPdf.setIconSize(QtCore.QSize(100, 100))
        self._btnProtectPdf.setAutoRepeat(False)
        self._btnProtectPdf.setAutoDefault(False)
        self._btnProtectPdf.setDefault(True)
        self._btnProtectPdf.setFlat(False)
        self._btnProtectPdf.setObjectName("_btnProtectPdf")
        self.horizontalLayout.addWidget(self._btnProtectPdf)
        self._btnExportPdf2SinglePdf = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnExportPdf2SinglePdf.sizePolicy().hasHeightForWidth())
        self._btnExportPdf2SinglePdf.setSizePolicy(sizePolicy)
        self._btnExportPdf2SinglePdf.setMinimumSize(QtCore.QSize(0, 60))
        self._btnExportPdf2SinglePdf.setStyleSheet("background-color: rgb(70, 148, 200);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/images/resources/images/pdf2pdf1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btnExportPdf2SinglePdf.setIcon(icon1)
        self._btnExportPdf2SinglePdf.setIconSize(QtCore.QSize(100, 100))
        self._btnExportPdf2SinglePdf.setObjectName("_btnExportPdf2SinglePdf")
        self.horizontalLayout.addWidget(self._btnExportPdf2SinglePdf)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(50, 25, 50, 25)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self._btnPdf2SeperatePdf = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnPdf2SeperatePdf.sizePolicy().hasHeightForWidth())
        self._btnPdf2SeperatePdf.setSizePolicy(sizePolicy)
        self._btnPdf2SeperatePdf.setMinimumSize(QtCore.QSize(0, 60))
        self._btnPdf2SeperatePdf.setStyleSheet("background-color: rgb(55, 49, 118);")
        self._btnPdf2SeperatePdf.setIcon(icon1)
        self._btnPdf2SeperatePdf.setIconSize(QtCore.QSize(100, 100))
        self._btnPdf2SeperatePdf.setObjectName("_btnPdf2SeperatePdf")
        self.horizontalLayout_2.addWidget(self._btnPdf2SeperatePdf)
        self._btnPng2Pdf = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnPng2Pdf.sizePolicy().hasHeightForWidth())
        self._btnPng2Pdf.setSizePolicy(sizePolicy)
        self._btnPng2Pdf.setMinimumSize(QtCore.QSize(0, 60))
        self._btnPng2Pdf.setStyleSheet("background-color: rgb(190, 0, 0);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/images/resources/images/png2pdf1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btnPng2Pdf.setIcon(icon2)
        self._btnPng2Pdf.setIconSize(QtCore.QSize(100, 100))
        self._btnPng2Pdf.setObjectName("_btnPng2Pdf")
        self.horizontalLayout_2.addWidget(self._btnPng2Pdf)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(100, 25, 100, 50)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self._btnExportPdf2Png = QtWidgets.QPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self._btnExportPdf2Png.sizePolicy().hasHeightForWidth())
        self._btnExportPdf2Png.setSizePolicy(sizePolicy)
        self._btnExportPdf2Png.setMinimumSize(QtCore.QSize(0, 60))
        self._btnExportPdf2Png.setStyleSheet("background-color: rgb(124, 0, 70);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/images/resources/images/pdf2png2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self._btnExportPdf2Png.setIcon(icon3)
        self._btnExportPdf2Png.setIconSize(QtCore.QSize(100, 100))
        self._btnExportPdf2Png.setObjectName("_btnExportPdf2Png")
        self.horizontalLayout_4.addWidget(self._btnExportPdf2Png)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self._btnProtectPdf.setText(_translate("Frame", "Protect Pdf"))
        self._btnExportPdf2SinglePdf.setText(_translate("Frame", "Export PDF \n"
"to Single Pdf"))
        self._btnPdf2SeperatePdf.setText(_translate("Frame", "Export Pdf \n"
"to Seperate Pdf"))
        self._btnPng2Pdf.setText(_translate("Frame", "Export PNG\n"
"to Pdf"))
        self._btnExportPdf2Png.setText(_translate("Frame", "Export Pdf \n"
"to PNG"))




if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = HomeFrame()
    window.setGeometry(600, 50, 800, 600)
    window.show()
    sys.exit(app.exec_())